

df1$TOTAL.INJURED <-
  df1$NUMBER.OF.PERSONS.INJURED +
  df1$NUMBER.OF.PEDESTRIANS.INJURED + 
  df1$NUMBER.OF.CYCLIST.INJURED +
  df1$NUMBER.OF.MOTORIST.INJURED

  
df1$TOTAL.FATALITIES <-
  df1$NUMBER.OF.PERSONS.KILLED +
  df1$NUMBER.OF.PEDESTRIANS.KILLED + 
  df1$NUMBER.OF.CYCLIST.KILLED +
  df1$NUMBER.OF.MOTORIST.KILLED

myvars <-
  c(
    "DATE",
    "TIME",
    "BOROUGH",
    "ZIP.CODE",
    "ON.STREET.NAME",
    "TOTAL.INJURED",
    "TOTAL.FATALITIES"
  )

df2<- df1[myvars]

