library(magrittr)
library(dplyr)
library(ggplot2)
install.packages('viridis')
library(viridis)
install.packages('plotly')
library(plotly)
install.packages('maps')
library(maps)
install.packages('rgeos')
library(rgeos)
install.packages('rgdal')
library(rgdal)
install.packages('ggthemes')
library(ggthemes)
library(crosstalk)
install.packages('leaflet')
library(leaflet)
install.packages('d3heatmap')
library(d3heatmap)
install.packages('rnoaa')
library(rnoaa)
install.packages('DT')
library(DT)
install.packages('googleVis')
library(googleVis)
#this package was not available in R 3.4.1
# install.packages('d3scatter')
# library(d3scatter)

